version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    environment:
      - BASE_FOLDER_ID=1E2R_jSVUfqadngolX-PJMNXUL9-Wm9kY
